### PR TITLE
Translation for PR

### PR DESCRIPTION
**Pull request by dav-is**
https://github.com/flarum/core/pull/1035

### CODE REVIEW

**Comment by maelsoucaze** [comment]
Why do not use lowercases on `Post`, `Discussion` and `Unaccounted`? :)

**Comment by dav-is** [comment]
@maelsoucaze That's the correct way to capitalize titles

**Comment by franzliedke** [comment]
That depends on [who you ask](https://twitter.com/cs_forum/status/771695753592991744) ;)

I don't think we need title case for such a low-level heading. /cc @dcsjapan @tobscure

**Comment by dcsjapan** [comment]
I agree with Franz. In the case of `posts_missing_head` and `discussions_missing_head` they're being used in the context of a sentence, so they should be lower case.

**Comment by dcsjapan** [comment]
Closing this since its counterpart https://github.com/flarum/core/pull/1035 has been closed.

**Pull request closed without merging**
