### PR TITLE
Flags are not languages! Replace SVG images with generic icon.

### PR DESCRIPTION
**Pull request by maelsoucaze**
Flags are symbols that represent countries or nations. Languages represent a shared method of communication between people. Flags are unique to a country or nation: but languages are often spoken across national borders. By using a flag for a language, you may confuse or even offend users.

Here's some reading: http://flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

This pull deletes the SVG image to replace it with a generic icon ([language](http://fortawesome.github.io/Font-Awesome/icon/language/) from Font Awesome), and removes the unecessary line ending normalization for SVG images, because there's none.

Icon (and background color) on the extension page:

extensionicon

### CODE REVIEW

**Comment by maelsoucaze** [comment]
Plus, the actual English language pack flag demonstrates especially that flags shouldn't be used, because it uses American English, not British one, but uses British flag. So it can be confusing. :)

**Comment by franzliedke** [comment]
Hmm, and which icon are other extensions supposed to use?

**Comment by maelsoucaze** [comment]
Other language packs? What's problem to use the same (as the language name is displayed below)? It will even be clearer on a admin side.

**Comment by rodymol123** [comment]
I tink it's better to use the flags, since several nations / countries have their own grammar and word-use. Flags distinguish these differences.

**Comment by johannsa** [comment]
Flags representing languages are widely used. Does that glyph from font awesome represents French better than the flag of France?

Note: American English should use better the United States' Flag rather than the Union Jack.

**Comment by maelsoucaze** [comment]
A language should not be represented, but a type of extension can be, so that's why the language icon it's used: it tells to admin that this extension translates the user interface, as simply as that (and that icon is pretty clear). The language name (in English) below is here to tell what's the language.

Plus, that's not because something is widely used that is good: IE was widely used, and it's a pain to maintain web application with it.

**Comment by dcsjapan** [comment]
The question seems to be:

Should the icon indicate what language is added? Or what kind of extension it is?

I think the latter could be indicated in other ways. Although language packs are indeed extensions in one sense, they also different from all other types of extensions in a couple of very important ways. Ideally, it would be best if the Extensions page of the ACP could be divided into categories, with language packs grouped together in a category of their own. If that happens, the language pack icon that @maelsoucaze suggests would merely repeat information available in the ACP interface: "This is a language pack."

At this point I think we should decide whether the Extensions page will (or will not) ultimately be divided into categories. If it will be divided, then I don't see why langpack creators shouldn't be free to choose whatever icon they think best expresses their product. If it won't, then it might be a good idea to use a uniform icon to identify language packs as such.

I guess that puts the ball in the court occupied by @tobscure and @franzliedke. :wink:

**Comment by johannsa** [comment]
@dcsjapan I could not agree more.

Using the proposed symbol to signal a place with multiple language options to adjust or to choose is  great but when it comes to represent individual languages in a graphical/visual (non-textual) form using flags as the **graphical/visual** representation of a language is a widely used convention. This is a fact and wether this is right or wrong, it is not up to us, same as trying to educate the user.

**Comment by tobscure** [comment]
We've discussed this and will change the icon for this language pack to the US flag. And to make it easier to distinguish between language packs and other extensions, we're going to divide extensions into categories on the extensions page – #746

**Pull request closed without merging**
