### PR TITLE
Adjust namespacing for Tags

### PR DESCRIPTION
**Pull request by dcsjapan**
- Removes existing first-level prefix and de-dents file.
- Adjusts key references to use new namespacing.

### CODE REVIEW

**Comment by tobscure** [comment]
👌

**Comment by dcsjapan** [comment]
@tobscure This is what the the YML files end up looking like. Note the difference between the references to `tags::ref.key_name` and `ref.key_name`, which is in core.

It occurred to me that we could add some commenting to the top of the file, to do things like:

- Identify what the resources belong to ("These resources are used by the Tags extension")
- Include some basic instructions on how to access the tags in code.

Do you think it would make sense to add this information?

**Comment by tobscure** [comment]
I think we can probably leave it to be explained in/inferred from the documentation.

**Comment by dcsjapan** [comment]
Okay.

**Pull request merged**
