### PR TITLE
Use reused translations and remove unnecessary double quotes

### PR DESCRIPTION
**Pull request by milescellar**
[See the discussion about these changes.](https://github.com/flarum/flarum-ext-english/pull/114)

### CODE REVIEW

**Comment by franzliedke** [comment]
*Actually*... sorry for going back and forth, I kinda think that the duplication in the texts for custom header and footer are merely coincidental and not conceptual. Thus, there is no pain in keeping them duplicated. What do you think, @tobscure ?

**Comment by milescellar** [comment]
@franzliedke My two cents:

For now, every duplicated content was put in reused translations, it's a sort of rule, no matter what is duplicated, coincidental or not.

If, in the future, these texts for custom header and footer are changed to something different, we can remove easily the reused translations and reuse unique strings which are still present. That's is exactly the purpose of that system, to change strings without core changes, so that's a minimal impact.

**Comment by franzliedke** [comment]
The point is that using this for every instance of duplication might add more complexity than necessary. Only things that change for the same reason, should be de-duped this way.

**Comment by franzliedke** [comment]
Dare I ping @dcsjapan for this question? ;)

**Comment by milescellar** [comment]
I understand your point of view, but don't forget that it will be easier to explain to translators (which are not developers) that *every* duplicated content is present in "reused translations".

If translators don't adapt their language pack with this rule in mind, they will just translate the content of reused translations without adapt the context of their language compared to the English one. Because of that, their localization will have no sense (on some languages). For example, in French, there are some extra (or removed) strings in "reused translations" compared to the English language pack due to the specificity of the language.

So, to be consistent:
- We have to explain that reused translations just means "translations which are used in multiple locations", no matter what, and that they can use this feature on their language packs.
- Or, if you want to get rid of the complexity issue, we can just remove reused translations, so translators will have to translate many times similar items (that's will be longer, but it will be logical and simple).

**Comment by tobscure** [comment]
I agree with @milescellar, I think the convention we've been using is that *every* duplicate translation should be in `ref`, regardless of context.

> Only things that change for the same reason, should be de-duped this way.

So in the case, would the custom header/footer text instances not change for the same reason? What's the difference between this case and, say, the `ref.email` translation (used as a placeholder, a heading, a menu item, etc.)?

That said, I must admit this is a little bit enticing:

> Or, if you want to get rid of the complexity issue, we can just remove reused translations, so translators will have to translate many times similar items (that's will be longer, but it will be logical and simple).

How much time do reused translations really save? Surely not much more than copy + paste?

**Comment by franzliedke** [comment]
The difference is between cases like "Discussion" and long strings like these. If we decide to change our terminology to, say, "threads", then we want to change all those occurrences in one place, because we are describing the same concept everywhere.

With these strings (description below the setting field, and intro text to a modal), this seems to be more coincidental.

But yes, these "rules" are hard to turn into explicit rules and might devolve into nit-picking. Simpler rules like "de-dupe everything that appears twice" or "don't de-dupe at all" are obviously easier to follow through with.
(And let's not forget the original intention: we want to allow for easy duplication of strings, without forcing them to be the same in different languages, and while making it easy to keep things consistent.)

So much thought went into all of this, I want to keep it pretty. 😭

**Comment by milescellar** [comment]
> How much time do reused translations really save? Surely not much more than copy + paste?

@tobscure Honestly? It's maybe even longer than a copy paste, because translators have to ensure the reused translation is okay with their language. In some languages, a word can have different meanings and vice versa.

> The difference is between cases like "Discussion" and long strings like these. If we decide to change our terminology to, say, "threads", then we want to change all those occurrences in one place, because we are describing the same concept everywhere.

@franzliedke Exactly, but tthis is not the case for now. For example, if you decide to change the "Discussion" string (which is present in reused translations) to "Thread", you have to change manually every occurrences of "Discussion" in every strings which are also not present in reused translations (like "Edit Discussion", "A-long-string-with-Discussion-term-in-the-sentence", etc.). So, in any case, you have to deal with a Ctrl+Shift+F in your text editor, reused translations or not.

---

Really, I like this "reused translations" feature, it's even often me who sends PR to include them... But, to be quite unbiased and honest, I do not think it's easy to understand and to use for translators. Even us, who discussed so much on this feature in the past, don't agree on how to use them properly.

So, in a point of view of a simple translator, I think it's better to remove them. 😢

**Comment by franzliedke** [comment]
Hmm, I'd like to merge this for now. But now we have conflicts, sorry for the long wait. :cry: 

@milescellar Can I ask you to rebase this so I can merge? :)

**Comment by tobscure** [comment]
Do we have a longer-term plan to remove the reused translation mechanism? Should I make an issue?

**Comment by franzliedke** [comment]
I still like it, to be honest.

**Comment by luceos** [comment]
@franzliedke i'm with you. I think the references are a great way to keep translations clean, even though they make readability harder. As such I'm against dropping the references in the long term, even though that means maintaining a custom Translator class.

**Comment by milescellar** [comment]
@franzliedke No more conflicts, it should be good! 👍

**Pull request merged**
