### PR TITLE
rename entries in Sort menu

### PR DESCRIPTION
**Pull request by renyuneyun**
(roughly) fix flarum/core#351

### CODE REVIEW

**Comment by franzliedke** [comment]
@tobscure Do you think this improves the situation? You did not voice your opinion in flarum/core#351.

**Comment by franzliedke** [comment]
Can I get some other opinions here? I don't like these long versions too much, but I acknowledge there is a problem with some of these short strings (and with making it clear that these options are about the sort order of the list).

**Comment by renyuneyun** [comment]
Well I'm not sure if there is a better way since they are discribing two different types ('reply' and 'discussion').

Regarding sort order, maybe (at least for now) changing `Recent replies` (the value of `latest_button`) to `Latest replies` would help.

**Comment by milescellar** [comment]
I don't like these long versions neither. For the French translation, I changed _Latest_ (`latest_button`) to _Activity_, but I don't know if it's clearer in English. The issue is, like @renyuneyun said, that don't describe the same "type".

**Comment by tobscure** [comment]
Currently the issue with the longer strings is a UI one, in that it makes the sorting dropdown much wider which is kind of ugly. (Not sure a sorting control needs to have that much prominence.)

So I think we should revisit this after the [discussion list revamp](https://discuss.flarum.org/d/2716-discussion-list-revamp) is implemented, where we will have the opportunity to tone down and/or relocate the sorting control. (It's not clear where it will be in the mockup, but I'm thinking just a small text-only button above the discussion list, with no background, as in [this mobile mockup](https://github.com/flarum/core/issues/867#issuecomment-198113531).)

**Comment by franzliedke** [comment]
I made a note over [in the revamp ticket](https://github.com/flarum/core/issues/867#issuecomment-279141399), so I am closing this for now.

Thanks for your effort, @renyuneyun.

**Pull request closed without merging**
