### PR TITLE
add yamllinter check

### PR DESCRIPTION
**Pull request by sijad**
more info about yamllinter:

https://github.com/sijad/yaml-translation-utils/tree/master/yamllinter

### CODE REVIEW

**Comment by tobscure** [comment]
One thought: we might not want to test `validation.yml` since this file should mirror Laravel's as closely as possible

**Comment by sijad** [comment]
> we might not want to test validation.yml since this file should mirror Laravel's as closely as possible

no worries.

one question though, for now it only checks keys level >= 2, some root level (e.g. core.admin, core.forum, core.email, etc) are not sorted, what about them?

**Comment by sijad** [comment]
now it ignores `validation.yml`

with a little colors to make it more readable.

**Comment by franzliedke** [comment]
Not too fussed, but feel free to merge.

**Comment by sijad** [comment]
should I send a PR with sorted keys?

**Comment by tobscure** [comment]
yes please

**Pull request merged**
